"""
bgfx - "Bring Your Own Engine/Framework" style rendering library, fork of https://github.com/bkaradzic/bgfx.
"""

module(
    name = "bgfx",
    version = "1.0.0",
    bazel_compatibility = [">=9.0.0"],
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "bx", version = "1.0.0")
bazel_dep(name = "bimg", version = "1.0.0")

git_override(
    module_name = "bx",
    branch = "master",
    remote = "https://github.com/cdbarrett/bx.git",
)

git_override(
    module_name = "bimg",
    branch = "master",
    remote = "https://github.com/cdbarrett/bimg.git",
)

# local_path_override(
#     module_name = "bx",
#     path = "../bx",
# )

# local_path_override(
#     module_name = "bimg",
#     path = "../bimg",
# )
