load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "shaderc",
    srcs = glob([
        "*.cpp",
        "*.h",
    ]),
    copts = [
        "-march=native",
        "-I3rdparty/dawn",
        "-I3rdparty/glslang",
        "-I3rdparty/glslang/glslang/Include",
        "-I3rdparty/glslang/glslang/Public",
    ],
    cxxopts = ["-std=c++20"],
    visibility = ["//visibility:public"],
    deps = [
        "//:bgfx",
        "//3rdparty/d3d4linux",
        "//3rdparty/dawn:tint",
        "//3rdparty/directx-headers",
        "//3rdparty/fcpp",
        "//3rdparty/glsl-optimizer",
        "//3rdparty/glslang",
        "//3rdparty/spirv-cross",
        "//3rdparty/spirv-tools",
        "@bx",
        "@bimg",
    ],
)
